trigger:
- Azure-main

pool:
  vmImage: ubuntu-latest

variables:
- group: CICD-Demo-var-group  # Link the variable group

steps:
#  Checkout Code from GitHub
- checkout: self
  displayName: "Checkout GitHub repository"

#  Login to Docker Hub
- script: |
    echo "Logging in to Docker Hub..."
    echo "login completed"
  displayName: "Login to Docker Hub"

