trigger:
- Azure-main

pool:
  vmImage: ubuntu-latest

variables:
- group: CICD-Demo-var-group  # Link the variable group

steps:
#  Checkout Code from GitHub
- task: Checkout@1
  displayName: "Checkout GitHub repository"

#  Login to Docker Hub
- script: |
    echo "Logging in to Docker Hub..."
    echo $(DOCKER_PASSWORD) | docker login -u arasu35 --password-stdin
  displayName: "Login to Docker Hub"

#  Build Docker Image
- script: |
    echo "Building the Docker image..."
    docker build -t arasu35/gatus-azure:latest -f ./Dockerfile .
    docker images
  displayName: "Build Docker Image"

#  Push Image to Docker Hub
- script: |
    echo "Tagging and pushing to Docker Hub..."
    docker tag arasu35/gatus-azure:latest arasu35/gatus-azure:latest
    docker push arasu35/gatus-azure:latest
  displayName: "Push Docker Image to Docker Hub"
