steps:
  # Login to Docker Hub
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'sh'
    args:
      - '-c'
      - 'echo $$DOCKER_PASSWORD | docker login -u arasu35 --password-stdin'
    secretEnv: ['DOCKER_PASSWORD']

  #  Build the Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'arasu35/gatus-gcp:latest', '.']

  #  Push the Image to Docker Hub
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'arasu35/gatus-gcp:latest']

availableSecrets:
  secretManager:
    - versionName: projects/cicd-live-demo/secrets/DOCKER_PASSWORD/versions/latest
      env: 'DOCKER_PASSWORD'

options:
  logging: CLOUD_LOGGING_ONLY
