web:
  base-path: /gatus 
endpoints:
  # Basic HTTP Check with Status Code & Response Time
  - name: dataclap-homepage
    url: "https://www.dataclap.digital/"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 500"

  # SSL Certificate Expiration Check
  - name: dataclap-ssl
    url: "https://www.dataclap.digital/"
    interval: 12h
    conditions:
      - "[CERTIFICATE_EXPIRATION] > 7d"

  # ICMP Ping Check (Only works if the server allows ping)
  - name: dataclap-ping
    url: "icmp://www.dataclap.digital"
    interval: 5m
    conditions:
      - "[CONNECTED] == true"

  # API or Specific Page Check (if applicable)
  - name: dataclap-api
    url: "https://www.dataclap.digital/api/status"
    interval: 2m
    conditions:
      - "[STATUS] == 200"
      - "[BODY].service == 'healthy'"
